services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    container_name: elasticsearch2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=true
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=changeme
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    container_name: kibana2
    environment:
      - SERVER_HOST=0.0.0.0
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  logstash:
    build: .
    image: docker.elastic.co/logstash/logstash:9.1.4
    container_name: logstash
    environment:
      - LS_JAVA_OPTS=-Xmx512m -Xms256m
      - CONFIG_RELOAD_AUTOMATIC=true
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./logstash/config/:/usr/share/logstash/config/
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./data:/data
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch
    networks:
      - elk


networks:
  elk:
    driver: bridge
    
volumes:
  es_data:
